//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LadderApp1 {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ArquivosFontesC {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ArquivosFontesC() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LadderApp1.ArquivosFontesC", typeof(ArquivosFontesC).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a //====================================================================================
        ///// Arquivo de definição geral
        ///// Autor: Silvano Fonseca Paganoto
        ///// Data: 15/09/2010
        /////====================================================================================
        ///
        ///
        ///#ifndef DEFINICAO_H_
        ///#define DEFINICAO_H_
        ///#define RECARGA_CCR0 10000
        /////====================================================================================
        ///// Includes
        /////===================================================================== [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string definicaoH {
            get {
                return ResourceManager.GetString("definicaoH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a //====================================================================================
        ///// Arquivo da Lista endereçso do usados no microcontrolador
        ///// Autor: Silvano Fonseca Paganoto
        ///// Data: 15/09/2010
        /////====================================================================================
        ///#ifndef ENDERECOS_H_
        ///#define ENDERECOS_H_
        ///
        /////====================================================================================
        ///// Includes
        /////===================================================================== [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string enderecosH {
            get {
                return ResourceManager.GetString("enderecosH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a //====================================================================================
        ///// Rotina de execução do contador
        /////====================================================================================
        ///void ExecContador(TContador *Contador)
        ///{
        ///	switch (Contador-&gt;Tipo)
        ///	{
        ///#EXECCONTADOR_TIPO0#
        ///#EXECCONTADOR_TIPO1#
        ///	default:
        ///		break;
        ///	}
        ///	if (Contador-&gt;EN == 0)
        ///		Contador-&gt;Pulso = 1;
        ///}
        ///.
        /// </summary>
        internal static string ExecContador_funcoesC {
            get {
                return ResourceManager.GetString("ExecContador_funcoesC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a void ExecContador(TContador *Contador);.
        /// </summary>
        internal static string ExecContador_funcoesH {
            get {
                return ResourceManager.GetString("ExecContador_funcoesH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 	case 0: // Contador Crescente
        ///		if (Contador-&gt;Reset == 1)
        ///		{
        ///			Contador-&gt;DN = 0;
        ///			Contador-&gt;Acumulado = 0;
        ///			Contador-&gt;Reset = 0;
        ///		}
        ///		if (Contador-&gt;EN == 1 &amp;&amp; Contador-&gt;Pulso == 1)
        ///		{
        ///			Contador-&gt;Pulso = 0;
        ///			if (Contador-&gt;Acumulado &lt;= 255)
        ///			{
        ///				Contador-&gt;Acumulado++;
        ///				if (Contador-&gt;Acumulado &gt;= Contador-&gt;Preset)
        ///					Contador-&gt;DN = 1;
        ///				else
        ///					Contador-&gt;DN = 0;
        ///			}
        ///		}
        ///		break;
        ///.
        /// </summary>
        internal static string ExecContador_Tipo0_funcoesC {
            get {
                return ResourceManager.GetString("ExecContador_Tipo0_funcoesC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 	case 1: // Contador Decrescente
        ///		if (Contador-&gt;Reset == 1)
        ///		{
        ///			Contador-&gt;Acumulado = Contador-&gt;Preset;
        ///		}
        ///		if (Contador-&gt;EN == 1 &amp;&amp; Contador-&gt;Pulso == 1)
        ///		{
        ///			Contador-&gt;Pulso = 0;
        ///			if (Contador-&gt;Acumulado &gt; 0)
        ///			{
        ///				Contador-&gt;Acumulado--;
        ///				if (Contador-&gt;Acumulado == 0)
        ///					Contador-&gt;DN = 1;
        ///
        ///				else
        ///					Contador-&gt;DN = 0;
        ///			}
        ///		}
        ///		break;
        ///.
        /// </summary>
        internal static string ExecContador_Tipo1_funcoesC {
            get {
                return ResourceManager.GetString("ExecContador_Tipo1_funcoesC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a //====================================================================================
        ///// Rotina de execução do temporizador
        /////====================================================================================
        ///void ExecTemporizador(TTemporizador *Temporizador)
        ///{
        ///	char EventoPresente = 0;
        ///	switch (Temporizador-&gt;Tipo)
        ///	{
        /////-----------------------------------------------------------------------
        ///#EXECTEMPORIZADOR_TIPO0#
        /////-----------------------------------------------------------------------
        ///#EXEC [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string ExecTemporizador_funcoesC {
            get {
                return ResourceManager.GetString("ExecTemporizador_funcoesC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a void ExecTemporizador(TTemporizador *Temporizador);
        ///.
        /// </summary>
        internal static string ExecTemporizador_funcoesH {
            get {
                return ResourceManager.GetString("ExecTemporizador_funcoesH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 	case 0:// TON ====================================================================
        ///
        ///		if ((Temporizador-&gt;EN) &amp;&amp; (!Temporizador-&gt;Reset))
        ///		{
        ///			//-------------------------------------------------------
        ///			if (Sistema.Evento10ms == 1)
        ///			{
        ///				(Temporizador-&gt;Parcial)++;
        ///				switch (Temporizador-&gt;Base)
        ///				{
        ///				case 0:
        ///					EventoPresente = 1;
        ///					break;
        ///				case 1:
        ///					if ((Temporizador-&gt;Parcial) &gt;= 10)
        ///						EventoPresente = 1;
        ///					break;
        ///				case 2:
        ///					if ((Temporizador-&gt;Parcial) &gt;= [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string ExecTemporizador_Tipo0_funcoes {
            get {
                return ResourceManager.GetString("ExecTemporizador_Tipo0_funcoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 	case 1: // TOFF
        ///		if (Temporizador-&gt;EN)
        ///		{
        ///			Temporizador-&gt;Acumulado = Temporizador-&gt;Preset;
        ///			Temporizador-&gt;DN = 1;
        ///		}
        ///		else
        ///		{
        ///			if (Sistema.Evento10ms)
        ///			{
        ///				(Temporizador-&gt;Parcial)++;
        ///				switch (Temporizador-&gt;Base)
        ///				{
        ///				case 0:
        ///					EventoPresente = 1;
        ///					break;
        ///				case 1:
        ///					if ((Temporizador-&gt;Parcial) &gt;= 10)
        ///						EventoPresente = 1;
        ///					break;
        ///				case 2:
        ///					if ((Temporizador-&gt;Parcial) &gt;= 100)
        ///						EventoPresente = 1;
        ///					break;
        ///				case 3:
        ///					if  [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string ExecTemporizador_Tipo1_funcoes {
            get {
                return ResourceManager.GetString("ExecTemporizador_Tipo1_funcoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a //====================================================================================
        ///// Rotina de execução do temporizador
        /////====================================================================================
        ///void ExecTemporizadores(void)
        ///{
        ///#TEMPORIZADORES#
        ///}.
        /// </summary>
        internal static string ExecTemporizadores_usuarioC {
            get {
                return ResourceManager.GetString("ExecTemporizadores_usuarioC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a void ExecTemporizadores(void);.
        /// </summary>
        internal static string ExecTemporizadores_usuarioH {
            get {
                return ResourceManager.GetString("ExecTemporizadores_usuarioH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a //====================================================================================
        ///// Arquivo de funções do sistema
        ///// Autor: Silvano Fonseca Paganoto
        ///// Data: 15/09/2010
        /////====================================================================================/*
        ///
        /////====================================================================================
        ///// Includes
        /////====================================================================================
        ///#include &quot;funcoes.h&quot;
        ///
        ///#EXECTEMPORIZADOR_C#
        ///
        ///#EXE [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string funcoesC {
            get {
                return ResourceManager.GetString("funcoesC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a //====================================================================================
        ///// Arquivo de prototipo das funções do sistema
        ///// Autor: Silvano Fonseca Paganoto
        ///// Data: 15/09/2010
        /////====================================================================================
        ///#ifndef FUNCOES_H_
        ///#define FUNCOES_H_
        /////====================================================================================
        ///// Includes
        /////====================================================================================
        ///#i [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string funcoesH {
            get {
                return ResourceManager.GetString("funcoesH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a //====================================================================================
        ///// Arquivo de interrupções do sistema
        ///// Autor: Silvano Fonseca Paganoto
        ///// Data: 15/09/2010
        /////====================================================================================/*
        ///
        /////====================================================================================
        ///// Includes
        /////====================================================================================
        ///#include &quot;usuario.h&quot;
        ///
        ///unsigned char AccMs = 0 [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string interrupcaoC {
            get {
                return ResourceManager.GetString("interrupcaoC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a //====================================================================================
        ///// Arquivo principal
        ///// Autor: Silvano Fonseca Paganoto
        ///// Data: 15/09/2010
        /////====================================================================================
        ///
        /////====================================================================================
        ///// Includes
        /////====================================================================================
        ///#include &quot;definicao.h&quot;
        ///#include &quot;setuphardware.h&quot;
        ///#include &quot;usua [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string mainC {
            get {
                return ResourceManager.GetString("mainC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a //====================================================================================
        ///// Arquivo de configuração do hardware
        ///// Autor: Silvano Fonseca Paganoto
        ///// Data: 15/09/2010
        /////====================================================================================
        ///
        /////====================================================================================
        ///// Includes
        /////====================================================================================
        ///#include &quot;setuphardware.h&quot;
        ///
        /////================ [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string setupHardwareC {
            get {
                return ResourceManager.GetString("setupHardwareC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a //====================================================================================
        ///// Arquivo de protótipo das funções para configuração de hardware
        ///// Autor: Silvano Fonseca Paganoto
        ///// Data: 15/09/2010
        /////====================================================================================
        ///
        ///#ifndef SETUPHARDWARE_H_
        ///#define SETUPHARDWARE_H_
        ///
        /////====================================================================================
        ///// Includes
        /////===================================================== [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string setupHardwareH {
            get {
                return ResourceManager.GetString("setupHardwareH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a //====================================================================================
        ///// Arquivo da rotina do usuário
        ///// Autor: Silvano Fonseca Paganoto
        ///// Data: 15/09/2010
        /////====================================================================================
        ///
        /////====================================================================================
        ///// Includes
        /////====================================================================================
        ///#include &quot;usuario.h&quot;
        ///
        /////============================= [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string usuarioC {
            get {
                return ResourceManager.GetString("usuarioC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a //====================================================================================
        ///// Arquivo de protótipo das funções do programa do usuario
        ///// Autor: Silvano Fonseca Paganoto
        ///// Data: 15/09/2010
        /////====================================================================================
        ///
        ///#ifndef USUARIO_H_
        ///#define USUARIO_H_
        ///
        /////====================================================================================
        ///// Includes
        /////======================================================================== [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string usuarioH {
            get {
                return ResourceManager.GetString("usuarioH", resourceCulture);
            }
        }
    }
}
